import { Room, Wall, Repair, PaintInventory } from '@/types';

export const mockRooms: Room[] = [
  { id: 'r1', name: '客厅', floor: '一层' },
  { id: 'r2', name: '主卧', floor: '二层' },
  { id: 'r3', name: '厨房', floor: '一层' },
  { id: 'r4', name: '儿童房', floor: '二层' },
];

export const mockWalls: Wall[] = [
  {
    id: 'w1',
    roomId: 'r1',
    name: '电视背景墙',
    material: '石膏板',
    primerBrand: '立邦',
    primerColor: '通用抗碱底漆',
    topcoatBrand: '立邦',
    topcoatColor: 'NN7830-4 奶咖色',
    topcoatHex: '#D4B896',
    constructionDate: '2023-05-15',
    contractor: '家和装饰',
    notes: '电视背景墙，有暗藏灯带，注意不要在龙骨位置打孔',
    photos: [],
  },
  {
    id: 'w2',
    roomId: 'r1',
    name: '沙发墙',
    material: '水泥砂浆',
    primerBrand: '多乐士',
    primerColor: '净味底漆',
    topcoatBrand: '多乐士',
    topcoatColor: '88YY 66/052 暖白色',
    topcoatHex: '#F5EFE0',
    constructionDate: '2023-05-15',
    contractor: '家和装饰',
    notes: '',
    photos: [],
  },
  {
    id: 'w3',
    roomId: 'r2',
    name: '床头背景墙',
    material: '硅藻泥',
    primerBrand: '兰舍',
    primerColor: '硅藻泥专用底涂',
    topcoatBrand: '兰舍',
    topcoatColor: 'SK-021 灰蓝色',
    topcoatHex: '#7A9BA7',
    constructionDate: '2023-06-20',
    contractor: '兰舍硅藻泥',
    notes: '硅藻泥材质，修补需要专用材料',
    photos: [],
  },
  {
    id: 'w4',
    roomId: 'r3',
    name: '餐厅墙面',
    material: '护墙板',
    primerBrand: '—',
    primerColor: '—',
    topcoatBrand: '索菲亚',
    topcoatColor: '浅胡桃木色',
    topcoatHex: '#B08050',
    constructionDate: '2023-04-10',
    contractor: '索菲亚全屋定制',
    notes: '实木护墙板，避免水浸泡',
    photos: [],
  },
  {
    id: 'w5',
    roomId: 'r4',
    name: '儿童房书桌墙',
    material: '石膏板',
    primerBrand: '立邦',
    primerColor: '儿童漆专用底漆',
    topcoatBrand: '立邦',
    topcoatColor: 'BO0070-4 天空蓝',
    topcoatHex: '#8FC4E0',
    constructionDate: '2023-07-01',
    contractor: '家和装饰',
    notes: '儿童漆，可擦洗',
    photos: [],
  },
];

export const mockRepairs: Repair[] = [
  {
    id: 'rp1',
    wallId: 'w1',
    date: '2025-11-10',
    location: '窗框左下角',
    issueType: '裂缝',
    materials: '立邦腻子粉、同色面漆、网格布',
    steps: '1. 清理裂缝两侧松散腻子 2. 贴网格布防裂 3. 批刮腻子两遍 4. 干透后打磨 5. 刷底漆 6. 上面漆两遍',
  },
  {
    id: 'rp2',
    wallId: 'w1',
    date: '2026-03-15',
    location: '窗框左下角（同上次位置）',
    issueType: '裂缝',
    materials: '立邦弹性腻子、同色面漆、牛皮纸',
    steps: '1. 清理裂缝 2. 填弹性腻子 3. 贴牛皮纸 4. 批刮面层腻子 5. 打磨刷漆',
    isRecurring: true,
  },
  {
    id: 'rp3',
    wallId: 'w2',
    date: '2025-12-20',
    location: '沙发背后墙面',
    issueType: '钉眼',
    materials: '腻子粉、同色面漆',
    steps: '1. 取出钉子 2. 腻子填补钉眼 3. 打磨平整 4. 补刷面漆',
  },
  {
    id: 'rp4',
    wallId: 'w3',
    date: '2026-01-05',
    location: '床头上方插座旁',
    issueType: '污渍',
    materials: '硅藻泥专用清洁膏、软布',
    steps: '1. 用干布擦拭表面浮尘 2. 少量清洁膏涂抹污渍处 3. 打圈清洁 4. 干布擦净',
  },
  {
    id: 'rp5',
    wallId: 'w4',
    date: '2026-02-08',
    location: '踢脚线上方',
    issueType: '起皮',
    materials: '木工胶、同色木蜡油',
    steps: '1. 轻轻掀起起皮部位 2. 注入木工胶 3. 用重物压实固定24小时 4. 修补边缘补涂木蜡油',
  },
  {
    id: 'rp6',
    wallId: 'w5',
    date: '2026-04-20',
    location: '书桌旁墙角',
    issueType: '霉斑',
    materials: '除霉剂、漂白水、防霉底漆、同色面漆',
    steps: '1. 除霉剂喷洒霉斑 2. 湿布擦拭干净 3. 晾干后检查腻子层 4. 刷防霉底漆 5. 补刷面漆',
  },
];

export const mockInventory: PaintInventory[] = [
  {
    id: 'p1',
    brand: '立邦',
    colorCode: 'NN7830-4',
    colorName: '奶咖色',
    hexColor: '#D4B896',
    openDate: '2025-11-10',
    location: '储物间第二层货架',
    remainingAmount: 2.5,
    unit: 'L',
  },
  {
    id: 'p2',
    brand: '多乐士',
    colorCode: '88YY 66/052',
    colorName: '暖白色',
    hexColor: '#F5EFE0',
    openDate: '2023-06-01',
    location: '储物间第二层货架',
    remainingAmount: 4,
    unit: 'L',
  },
  {
    id: 'p3',
    brand: '立邦',
    colorCode: 'BO0070-4',
    colorName: '天空蓝',
    hexColor: '#8FC4E0',
    openDate: '2026-04-20',
    location: '储物间第三层货架',
    remainingAmount: 1.2,
    unit: 'L',
  },
  {
    id: 'p4',
    brand: '兰舍',
    colorCode: 'SK-021',
    colorName: '灰蓝色',
    hexColor: '#7A9BA7',
    openDate: '2026-01-05',
    location: '储物间第三层货架',
    remainingAmount: 0.8,
    unit: 'kg',
  },
];
